[workspace]
resolver = "2"
members = [
    "examples/cube",
    "examples/gltf",
    "examples/scene-viewer",
    "rend3",
    "rend3-gltf",
    "rend3-pbr",
    "rend3-pbr-bake",
    "rend3-types"
]

[profile.release]
debug = true
lto = "thin"

[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", rev = "b679342d9e62e50eff307d785590ffcbcc39b0d8" }
wgpu-core = { git = "https://github.com/gfx-rs/wgpu.git", rev = "b679342d9e62e50eff307d785590ffcbcc39b0d8" }
wgpu-hal = { git = "https://github.com/gfx-rs/wgpu.git", rev = "b679342d9e62e50eff307d785590ffcbcc39b0d8" }
wgpu-types = { git = "https://github.com/gfx-rs/wgpu.git", rev = "b679342d9e62e50eff307d785590ffcbcc39b0d8" }
# wgpu = { git = "https://github.com/cwfitzgerald/wgpu.git", rev = "b74eba93e2af25e0b562c9d40f941bbbc486ba19" }
# wgpu-core = { git = "https://github.com/cwfitzgerald/wgpu.git", rev = "b74eba93e2af25e0b562c9d40f941bbbc486ba19" }
# wgpu-hal = { git = "https://github.com/cwfitzgerald/wgpu.git", rev = "b74eba93e2af25e0b562c9d40f941bbbc486ba19" }
# wgpu-types = { git = "https://github.com/cwfitzgerald/wgpu.git", rev = "b74eba93e2af25e0b562c9d40f941bbbc486ba19" }
# wgpu = { path = "../wgpu/wgpu" }
# wgpu-core = { path = "../wgpu/wgpu-core" }
# wgpu-hal = { path = "../wgpu/wgpu-hal" }
# wgpu-types = { path = "../wgpu/wgpu-types" }
